# Generated by Django 3.2.5 on 2021-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlinename', models.ManyToManyField(blank=True, related_name='airlinename', to='flightope.airline')),
                ('airtype', models.ManyToManyField(blank=True, related_name='airtype', to='flightope.aircraft')),
                ('fromlocation', models.ManyToManyField(blank=True, related_name='fromlocation', to='flightope.city')),
                ('tolocation', models.ManyToManyField(blank=True, related_name='tolocation', to='flightope.city')),
            ],
        ),
    ]
